### ISSUE TITLE
Pilih data seko dataMaster

### ISSUE THREAD

**Issue by imakin** [fnugrahendi/petuk.corp#5]
ndro, nek misal input seko data2 datamaster nganggo QPushButton instead of QLineEdit piye ndro?
clear e nganggo setText("")
Misal line edit mu `self.le_Pembelian_OrderPembelian_TambahProduk_Input_Nama` dadi 
`self.tb_Pembelian_OrderPembelian_TambahProduk_Input_Nama`

trs tinggal gawe fungsi kaya ngene

``` python
def Pembelian_OrderPembelian_TambahProduk(self):
        data = []
        def isi():
            self.tb_Pembelian_OrderPembelian_TambahProduk_Input_Nama.setText(str(data[0]))
        def batal():
            self.tb_Pembelian_OrderPembelian_TambahProduk_Input_Nama.setText("-")
        self.DataMaster_DataNamaAlamat_Popup_Pilih(data,isi,batal)
```

trus tinggal connect 
`self.tb_Pembelian_OrderPembelian_TambahProduk_Input_Nama.clicked.connect(self.Pembelian_OrderPembelian_TambahProduk)`

**Comment by fnugrahendi** [comment]
bole zuga kin.bariki tek jajale

**Comment by fnugrahendi** [comment]
wih dadi jon.
terbaik lah kau jon.

**Comment by imakin** [comment]
haha tenan? mantap... style e paling ngene kiye 

``` css
QPushButton{
     border-style:inset;
     border-width:1px;
     border-radius:2px;
     border-color:rgb(156, 156, 156);
     background-color:#ffffff;
     min-height:23px;
}
```

nek sisan karo QLineEdit seframe `QLineEdit,QPushButton{border-style:inset;border-width:1px;border-radius:2px;border-color:rgb(156, 156, 156);background-color:#ffffff;min-height:23px;}` :hankey:
